### ISSUE TITLE
some usage questions

### ISSUE THREAD

**Issue by eins78** [parshap/js-opc#2]
(Posted here so others may find it and because it [exceeds 140 characters](https://twitter.com/parshap/status/598886194429038592)…)

Background: I am using `opc` in an app that controls 'sections' of pixels according to some configurable logic. I wrote a very simple/naive abstraction on top of it (1 section = 1 strand), and I am using that to get a feeling for how a higher-level OPC package could look (internally and externally).

So far, the prototype is working fine, but some questions arose from that:
- Buffers: As in your example, I am simply looping over every pixel in a strand and set its color, even when I want to set them all to the same color. Is that the recommended way to do it or does it just make for a very simple example? (This question might make more sense in the context of the next one).
- Coordination: A very general question, but maybe there is an easy answer: Do I have to care at all about coordinating all the calls I make to set pixels vs. when I write those pixels to the stream?
  To my surprise, it just worked; I would have expected issues when writing to 2 strands at the same time and writing a "half-finished" stream to the buffer. On the other hand with a local simulator everything is so fast that I might just not see any weird things going on. I have absolutely no intuition about this, so: should I coordinate inside the lib to not do any concurrent writes?
- Callbacks:  Another point where I might just be confused: Upon first look, I expected `stream.writePixels` to take a `callback(err, res)`, but it doesn't. Is that because it wouldn't make sense conceptually or just because it wasn't needed till now?

All 3 questions can be summarised as "should I now take the time to learn more about buffers/net/streams or will it just be fine" ;)

**Comment by parshap** [comment]
> Background: I am using opc in an app that controls 'sections' of pixels according to some configurable logic. I wrote a very simple/naive abstraction on top of it (1 section = 1 strand), and I am using that to get a feeling for how a higher-level OPC package could look (internally and externally).

Cool! That's sounds right so far. Are you creating one big strand and then using `strand.slice()` to get a strand object per "section of pixels"?

> - Buffers: As in your example, I am simply looping over every pixel in a strand and set its color, even when I want to set them all to the same color. Is that the recommended way to do it or does it just make for a very simple example?

When an opc message is sent, the current state of all pixel colors is included. The `strand.buffer` object represents that state, so every time you call `stream.writePixels()`, you send the data currently in that buffer. To set all colors the same, you you call `strand.setPixel()` once for every pixel you want to set. You can use a `for` loop to do this.

> Coordination: A very general question, but maybe there is an easy answer: Do I have to care at all about coordinating all the calls I make to set pixels vs. when I write those pixels to the stream?
> To my surprise, it just worked; I would have expected issues when writing to 2 strands at the same time and writing a "half-finished" stream to the buffer. On the other hand with a local simulator everything is so fast that I might just not see any weird things going on. I have absolutely no intuition about this, so: should I coordinate inside the lib to not do any concurrent writes?

Because the opc protocol requires all pixel colors to be sent in every message, when you call `stream.writePixels()`, the current pixel color state of your `strand` object is sent. Calling `stream.writePixels()` basically sets the color of your physical LEDs to match the current state of your `strand` object.

> Callbacks: Another point where I might just be confused: Upon first look, I expected stream.writePixels to take a callback(err, res), but it doesn't. Is that because it wouldn't make sense conceptually or just because it wasn't needed till now?

The _opc_ module doesn't handle any of the networking or async logic at all. Calling `stream.writePixels()` simply generates binary opc protocol data to be sent to some opc server. It's the network socket you create and pipe the opc stream into that handles the networking and async logic. You can listen for error events (`socket.on("error")`) or use a more sophisticated stream to manage control flow.

Hope that helps, but I'm not sure if I'm answering your questions directly. Let me know if I can clarify.
